z = {

"A": [

"acrylonitrilebutadienestyrene",
"antiestablishmentarianism",
"arenariamelanocephala",
"alkylbenzenesulfonate",
"antiestablishmentism",
"abetalipoproteinemia",
"adrenocorticotrophic",
"adrenocorticotrophin",
"adrenocorticotropic",
"adrenocorticotropin",
"auriculoventricular",
"adenocarcinomatous",
"agammaglobulinemia",
"antiferromagnetism",
"anticholinesterase",
"anthropocentricity",
"arteriolosclerosis",
"alphaadrenoceptor",
"antiferromagnetic",
"antiauthoritarian",
"anachronistically",
"australopithecine",
"absentmindedness",
"anthropomorphism",
"anthropomorphous",
"anthropomorphise",
"anthropomorphize",
"advantageousness",
"acquaintanceship",
"alcoholdependent",
"actinomycetaceae",
"abdominocentesis",
"ambidextrousness",
"anathematisation",
"anathematization",
"ancylostomatidae",
"aminotransferase",
"alstroemeriaceae",
"anglocatholicism",
"anthropometrical",
"antiinflammatory",
"apprehensiveness",
"autofluorescence",
"autobiographical",
"autoradiographic",
"appreciativeness",
"antiredeposition",
"antihypertensive",
"alphalipoprotein",
"australopithecus",
"authoritarianism",
"affectionateness",
"atrichornithidae",
"atrioventricular",
"administratively",
"attentiongetting",
"anesthesiologist",
"aristolochiaceae",
"antagonistically",
"arteriosclerosis",
"arteriosclerotic",
"antiintellectual",
"aristocratically",
"aciculignosa"],

"B": [

"buckminsterfullerene",
"bacteriochlorophyll",
"ballistocardiograph",
"ballistocardiogram",
"bicyclebuiltfortwo",
"batrachomyomachia",
"beggarmyneighbour",
"bosniaherzegovina",
"branchiobdellidae",
"brokenheartedness",
"beggarmyneighbor",
"benzylpenicillin",
"bronchopneumonia",
"brownishspeckled",
"bureaucratically"],

"C": [

"chlorobenzylidenemalononitrile",
"constructivemetabolic",
"compartmentalisation",
"compartmentalization",
"counterdemonstration",
"counterrevolutionary",
"counterrevolutionist",
"cartilaginification",
"chromatographically",
"chromoblastomycosis",
"contemporaneousness",
"conventionalisation",
"conventionalization",
"corticohypothalamic",
"counterdemonstrator",
"counterintelligence",
"countertransference",
"crossclassification",
"crosslinguistically",
"cytophotometrically"],

"D": [

"dichlorodiphenyltrichloroethane",
"dihydroxyphenylalanine",
"destructivemetabolic",
"diethylstilbesterol",
"diethylstilboestrol",
"dihydrostreptomycin",
"diethylmalonylurea",
"diethylstilbestrol",
"disenfranchisement",
"disproportionately",
"drunkanddisorderly",
"dimethylglyoxime",
"discombobulation",
"discombobulated",
"downwardarching",
"downwardsloping",
"disappointingly",
"disappointedly",
"deteminedly",
"dramatically",
"deflagrate"],

"E": [

"electroencephalographic",
"electroencephalograph",
"establishmentarianism",
"electroencephalogram",
"electrocardiographic",
"echoencephalography",
"electrocardiography",
"encephalomeningitis",
"echoencephalograph",
"electrocardiograph",
"electrodynamometer",
"enterobacteriaceae",
"electrodeposition",
"electromechanical",
"electronegativity",
"electroretinogram",
"electrostatically",
"eleutherodactylus",
"entomophthoraceae",
"extraordinariness",
"electricity"],

"F": [

"firstcomefirstserve",
"finnougricspeaking",
"fibrocartilaginous",
"fireonthemountain",
"footstepsofspring",
"fairmaidsoffrance",
"feeblemindedness",
"faintheartedness",
"foresightfulness",
"funeralresidence",
"fundamentalistic",
"fictionalisation",
"fictionalization",
"fremontodendron",
"foresightedness",
"flemishspeaking",
"flavoursomeness",
"flavourlessness",
"flowersofanhour",
"forthcomingness",
"fourdimensional",
"fasciolopsiasis",
"flibbertigibbet",
"familiarisation",
"familiarization",
"flatusrelieving"],

"G": [

"glottochronological",
"goodneighbourliness",
"glomerulonephritis",
"gastroenterologist",
"gastroenterostomy",
"gillovertheground",
"governmentinexile",
"glottochronology",
"goodhumouredness",
"goodtemperedness",
"gradeappropriate",
"grassofparnassus",
"gentlemanatarms",
"goodhumoredness",
"grandiloquently",
"grossulariaceae",
"germanspeaking",
"glucocorticoid",
"gonorhynchidae"],

"H": [

"hyperbetalipoproteinemia",
"hydrochlorofluorocarbon",
"hypobetalipoproteinemia",
"hundredandseventyfifth",
"hundredandthirtyfifth",
"hundredandtwentyfifth",
"hypogammaglobulinemia",
"hundredandseventieth",
"hundredandsixtyfifth",
"hundredandfiftyfifth",
"hundredandfortyfifth",
"heterobasidiomycetes",
"hyperlipoproteinemia",
"hypercholesterolemia",
"histoincompatibility",
"hypolipoproteinemia",
"hyperadrenocorticism",
"hysterosalpingogram",
"hypoadrenocorticism",
"hyperparathyroidism",
"hydroxytetracycline",
"hydrochlorothiazide",
"hundredandninetieth",
"hundredandeightieth",
"hundredandfifteenth",
"hundredandtwentieth",
"hemidemisemiquaver",
"homobasidiomycetes",
"hypoparathyroidism",
"hypercholesteremia",
"hyperbilirubinemia",
"hyperaldosteronism",
"hydroxychloroquine",
"hydroflumethiazide",
"histocompatibility",
"hundredandsixtieth",
"hundredandfiftieth",
"hundredandfortieth",
"hundredandthirtieth"],

"I": [

"immunoelectrophoresis",
"immunohistochemistry",
"iodochlorhydroxyquin",
"incontrovertibleness",
"internationalization",
"internationalisation",
"indistinguishability",
"incomprehensibility",
"interchangeableness",
"interdenominational",
"intellectualisation",
"intellectualization",
"individualistically",
"incontrovertibility",
"intercommunication",
"interconnectedness",
"internationalistic"],

"J": [

"jurisprudentially",
"jungermanniaceae",
"japanesespeaking",
"journalistically",
"jungermanniales",
"jackinthepulpit",
"jurisprudential",
"judeochristian",
"jewishorthodox",
"jackknifefish",
"juncaginaceae",
"justification",
"justificatory",
"journalistic",
"johnnyjumpup",
"javanthropus",
"johannesburg",
"journeyman"],

"K": [

"kissmeoverthegardengate",
"keratoconjunctivitis",
"knockdownanddragout",
"knowledgeableness",
"knockdowndragout",
"krypterophaneron",
"knowledgeability",
"kinaesthetically",
"kannadaspeaking",
"keratoacanthoma",
"kindheartedness",
"kaleidoscopical",
"kinesthetically",
"keratoscleritis",
"knickerbockers",
"kalotermitidae",
"kilovoltampere",
"kindergartener",
"keratinization",
"keratinisation",
"knowledgeable",
"kilogrammeter",
"kangaskhanite",
"kenyapithecus",
"klyuchevskaya",
"knickknackery",
"kinanesthesia",
"kindergartner",
"karlmarxstadt",
"keratomycosis",
"keratomalacia",
"kittycornered",
"kinosternidae",
"kaleidoscopic"],

"L": [

"laryngotracheobronchitis",
"lipochondrodystrophy",
"languedocroussillon",
"largecapitalisation",
"largecapitalization",
"latespringblooming",
"laryngopharyngitis",
"lactobacteriaceae",
"laryngopharyngeal",
"lepidopterologist",
"leukoencephalitis",
"logogrammatically",
"lumpenproletariat",
"lawfullybegotten",
"loveliesbleeding",
"labourintensive",
"luxembourgville",
"lymphadenopathy"],

"M": [

"methylenedioxymethamphetamine",
"microgrammapiloselloides",
"markazuddawawalirshad",
"mucopolysaccharidosis",
"magnetohydrodynamics",
"makataimeshekiakiak",
"meningoencephalitis",
"mercurycontaminated",
"medroxyprogesterone",
"methyltestosterone",
"mucopolysaccharide",
"muscivoraforficata",
"machineaccessible",
"mammothermography",
"macrorhamphosidae",
"machinecontrolled",
"massspectrometric",
"materialistically",
"maxillomandibular",
"micropaleontology",
"mineralocorticoid",
"misinterpretation",
"misrepresentation",
"mostfavorednation",
"motherofthousands",
"multicollinearity",
"multitudinousness",
"monosyllabically",
"metalliccoloured"],

"N": [

"noninstitutionalised",
"noninstitutionalized",
"nephroangiosclerosis",
"nonrepresentational",
"noninterchangeable",
"nonprognosticative",
"neurophysiological",
"neuropsychological",
"nitrochloromethane",
"noncomprehensively",
"newcastleupontyne",
"neurofibromatosis",
"nondenominational",
"nonrepresentative",
"nitrobacteriaceae"],

"O": [

"otorhinolaryngologist",
"oophorosalpingectomy",
"onehundredthousandth",
"onehundredmillionth",
"obsessivecompulsive",
"otorhinolaryngology",
"orderchenopodiales",
"oxidationreduction",
"oversimplification",
"overcapitalization",
"overcapitalisation",
"objectionableness",
"onedimensionality",
"osteoglossiformes",
"outwarddeveloping",
"ornithorhynchidae",
"oversensitiveness",
"onequadrillionth",
"onequintillionth",
"onedimensional",
"orangeflowered"],

"P": [

"pneumonoultramicroscopicsilicovolcanoconiosis",
"polytetrafluoroethylene",
"pentamethylenetetrazol",
"polyvinylformaldehyde",
"pseudohermaphroditism",
"palatopharyngoplasty",
"paleoanthropological",
"pseudohermaphroditic",
"pseudohermaphrodite",
"pseudohallucination",
"parasympathomimetic",
"phenylpropanolamine",
"professionalisation",
"professionalization",
"phacoemulsification",
"penicillinresistant",
"pellitoryofthewall",
"pseudopleuronectes",
"plasmodiophoraceae",
"psychotherapeutics",
"pteridospermaphyta",
"profitmaximising"],

"Q": [

"quatercentennial",
"quantifiability",
"quarrelsomeness",
"quatercentenary",
"quantification",
"quincentennial",
"quinquefoliate",
"quintessential",
"quadrillionth",
"quasiparticle",
"quartermaster",
"quintillionth",
"questionnaire"],

"R": [

"radiopharmaceutical",
"resorcinolphthalein",
"radiocommunication",
"recruitingsergeant",
"rhinolaryngologist",
"ringaroundtherosy",
"rhinolaryngology",
"recurvirostridae",
"rhabdomyosarcoma",
"roentgenographic",
"radioimmunoassay",
"reddishlavender",
"righthandedness",
"reafforestation"],

"S": [

"schizosaccharomycetaceae",
"straightfromtheshoulder",
"semiautobiographical",
"sternocleidomastoid",
"schizosaccharomyces",
"surfaceassimilative",
"smallcapitalization",
"smallcapitalisation",
"sociolinguistically",
"saccharomycetaceae",
"selfaggrandizement",
"selfaggrandisement",
"sentimentalization",
"shouldertoshoulder",
"spectrographically",
"shockabsorbent"],

"T": [

"tetrabromophenolsulfonephthalein",
"tetrahydrocannabinol",
"threedimensionality",
"thirddimensionality",
"triphosphopyridine",
"tetramethyldiarsine",
"tetrafluoroethylene",
"tetrachloromethane",
"tetraiodothyronine",
"tarredandfeathered",
"transmogrification",
"transubstantiation",
"trichlormethiazide",
"triphosphopyridine",
"twinpropellerplane",
"territorialisation",
"territorialization",
"telecommunication",
"thermoacidophile",
"thermodynamics"],

"U": [

"uvulopalatopharyngoplasty",
"uncharacteristically",
"uncommunicativeness",
"unconscientiousness",
"unselfconsciousness",
"ultracentrifugation",
"unpleasantsmelling",
"unquestionableness",
"unsatisfactoriness",
"unconstitutionally",
"unenthusiastically",
"ultranationalistic"],

"V": [

"valetudinarianism",
"vasoconstriction",
"vasoconstrictive",
"vicepresidential",
"vespertilionidae",
"venturesomeness",
"velvetyplumaged",
"vasoconstrictor",
"voyeuristically",
"vasovesiculitis"],

"W": [

"watermelonshaped",
"wholeheartedness",
"wellproportioned",
"weatherstripping",
"wrinkleresistant",
"warmheartedness",
"whatchamacallum",
"wittgensteinian",
"worldshattering",
"winterflowering",
"wellintentioned",
"weatherboarding",
"weatherstripped",
"whatchamacallit",
"welwitschiaceae"],

"X": [

"xenotransplantation",
"xanthorrhoeaceae",
"xeroradiography",
"xenotransplant",
"xanthomatosis",
"xerophthalmia",
"xerophthalmus",
"xanthophyceae",
"xenosauridae"],

"Y": [

"yellowishorange",
"yellowblindness",
"yerwamaiduguri",
"yeniseisamoyed",
"youngbegetting",
"yellowishwhite",
"yellowishbeige",
"yekaterinoslav",
"yellowspotted",
"yellowishgray",
"yellowishgrey",
"yellowbellied",
"yellowstriped",
"yellowhammer",
"yuraksamoyed",
"yellowmarked",
"yankeedoodle",
"yellowbanded",
"youngbearing",
"yelloworange",
"youthfulness",
"yellowtinged",
"yellowtipped",
"yarnspinning",
"yellowthroat",
"yamoussukro",
"yellowbrown",
"yevtushenko",
"yellowstone",
"yellowgreen",
"yellowbeige",
"yastrzemski",
"yellowknife",
"yugoslavian",
"yellowwhite",
"youngblood",
"yellowbird"],

"Z": [

"zannichelliaceae",
"zygophyllaceae",
"zoroastrianism",
"zygnemataceae",
"zingiberaceae",
"zinjanthropus",
"zooflagellate",
"zygomycotina",
"zygomorphous",
"zygnematales",
"zoomastigina",
"zoomastigote",
"zantedeschia",
"zannichellia",
"zoomorphism",
"zanthoxylum",
"zygomorphic",
"zygophyllum",
"zooplankton",
"zygomycetes",
"zinnwaldite",
"zosteraceae",
"zonotrichia",
"zoroastrian",
"zestfulness",
"zarathustra",
"zalcitabine"]
}

print("Press any key to type long words.\nPress ctrl + alt + r to reset word database.\nPress ctrl + alt + b to quit.")

import keyboard
import copy
import win32com.client
from time import sleep, time
import os
# import pyscreenshot as ImageGrab
# from PIL import Image
# import numpy as np

shell = win32com.client.Dispatch("WScript.Shell")

for i in range(65, 91): # Sort words by shortest to longest
    z[chr(i)].sort(key = len)

words = copy.deepcopy(z)
current_time = time()


while True:
    # image = ImageGrab.grab(bbox = (935, 312, 975, 352))  # X1, Y1, X2, Y2
    # image.save(f"C:/kkutu_word_screenshot.png")
    # word = Image.open("C:/kkutu_word_screenshot.png")
    # numpy_word = np.array(word)

    for i in range(65, 91):
        if keyboard.is_pressed(chr(i+32)) and not keyboard.is_pressed("ctrl+alt+b") and not keyboard.is_pressed("ctrl+alt+r"):
            try:
                current_word = words[chr(i)][-1]
                words[chr(i)].pop()
                for j in range(1, len(current_word)):
                    shell.SendKeys(current_word[j])
                    for _ in range(100000): pass
                shell.SendKeys("{enter}")
                sleep(0.1)
            except: pass
    if keyboard.is_pressed("ctrl+alt+r"):
        words = copy.deepcopy(z)
    if keyboard.is_pressed("ctrl+alt+b"):
        break
    sleep(0.001)
exit